MissionImpossible-war/src/java/managed/AccountController.java
/**
 * BE Java EE "Mission Impossible"
 * Mineure "développement web"
 * CentraleSupélec, campus de Rennes
 * 
 * @author Guillaume Piolle <guillaume.piolle@centralesupelec.fr>
 * 2016
 */
package managed;

import agents.AccountRemote;
import java.io.Serializable;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

/**
 * "Managed bean" pour gérer un compte utilisateur.
 *
 * @author Guillaume Piolle <guillaume.piolle@centralesupelec.fr>
 */
@ManagedBean(name="accountController")
public class AccountController implements Serializable {
    
    /**
     * Juste pour éviter un warning.
     */
    private static final long serialVersionUID = 1L;
    
    /**
     * EJB encapsulant le compte de l'utilisateur connecté.
     */
    @EJB
    private AccountRemote account;

    /**
     * Constructeur par défaut.
     */
    public AccountController() {
    }
    
    /**
     * Récupération du login de l'utilisateur actuellement connecté.
     * @return Le login de l'utilisateur.
     */
    public String getUsername() {
        return account.getUsername();
    }
    
    /**
     * Déconnexion de l'utilisateur.
     * @return "Outcome" de navigation correspondant à un rechargement de la 
     * page d'accueil, pour prendre en compte la déconnexion.
     */
    public String logout() {
        FacesContext fc = FacesContext.getCurrentInstance();
        if (fc != null) {
            ExternalContext ec = fc.getExternalContext();
            if (ec != null) {
                ec.invalidateSession(); // Lance un NPE sans conséquence : bug Glassfish, apparemment (https://java.net/jira/browse/GLASSFISH-21166)
            }
        }
        return "/index.xhtml?faces-redirect=true";
    }
    
}

MissionImpossible-war/web/admin/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Mission: Impossible -- Pour une gestion moderne des déplacements professionnels</title>
        <h:outputStylesheet name="style.css"/>
    </h:head>
    <h:body>
        <f:view>
            <h1>Mission: Impossible</h1>
            <h2>Interface d'administration</h2>
            <p>
                vous êtes authentifié(e) en tant que <h:outputLabel value="#{accountController.username}" />
            </p>

            <h3>Missions connues du système</h3>
            <p><strong>À supprimer à terme&nbsp;: ne fait pas partie du cahier des charges, aucun agent ne devrait avoir accès à cette liste.</strong></p>
            <h:form id='attribution'>
                <h:dataTable value="${missionListController.getMissions()}" var="mission">
                    <h:column>
                        <h:outputText value="${mission.id}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.lieu}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.date}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.agent}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.agentAdmin}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.etat}" />
                    </h:column>
                </h:dataTable>
            </h:form>

            <h3>Missions demandées</h3>
            <h:form id='demandes'>
                <h:dataTable value="${missionListController.getMissionsDemandees()}" var="mission">
                    <h:column>
                        <h:outputText value="${mission.id}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.lieu}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.date}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.agent}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.etat}" />
                    </h:column>
                    <h:column>
                        <h:commandLink action="#{missionListController.attribuer(mission, 'admin1')}" value="S'attribuer la mission" />
                    </h:column>
                </h:dataTable>
            </h:form>
            

            <h3>Les missions que vous suivez</h3>
            <p>Missions Attribuées</p>
            <h:form id='attribuee'>
                <h:dataTable value="${missionListController.getMissionsParEtatSuiviesPar('ATTRIBUEE', 'admin1')}" var="mission">
                    <h:column>
                        <h:outputText value="${mission.id}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.lieu}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.date}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.agent}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.etat}" />
                    </h:column>
                    <h:column>
                        <h:commandLink action="#{missionListController.valider(mission)}" value="Valider la mission" />
                    </h:column>
                    <h:column>
                        <h:commandLink action="#{missionListController.refuser(mission)}" value="Refuser la mission" />
                    </h:column>
                </h:dataTable>
            </h:form>
            
            <p>Missions Validées</p>
            <h:form id='validee'>
                <h:dataTable value="${missionListController.getMissionsParEtatSuiviesPar('VALIDEE', 'admin1')}" var="mission">
                    <h:column>
                        <h:outputText value="${mission.id}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.lieu}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.date}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.agent}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.etat}" />
                    </h:column>
                </h:dataTable>
            </h:form>
            
            <p>Missions en cours</p>
            <h:form id='en_cours'>
                <h:dataTable value="${missionListController.getMissionsParEtatSuiviesPar('EN_COURS', 'admin1')}" var="mission">
                    <h:column>
                        <h:outputText value="${mission.id}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.lieu}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.date}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.agent}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.etat}" />
                    </h:column>
                    <h:column>
                        <h:commandLink action="#{missionListController.payer(mission)}" value="Mise en paiement" />
                    </h:column>
                </h:dataTable>
            </h:form>
            
            <p>Missions Payées</p>
            <h:form id='payee'>
                <h:dataTable value="${missionListController.getMissionsParEtatSuiviesPar('PAYEE', 'admin1')}" var="mission">
                    <h:column>
                        <h:outputText value="${mission.id}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.lieu}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.date}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.agent}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.etat}" />
                    </h:column>
                </h:dataTable>
            </h:form>
            
            <p>Missions Refusées</p>
            <h:form id='refusee'>
                <h:dataTable value="${missionListController.getMissionsParEtatSuiviesPar('REFUSEE', 'admin1')}" var="mission">
                    <h:column>
                        <h:outputText value="${mission.id}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.lieu}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.date}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.agent}" />
                    </h:column>
                    <h:column>
                        <h:outputText value="${mission.etat}" />
                    </h:column>
                </h:dataTable>
            </h:form>
            

            <p> 
                <ul>
                    <li><h:link outcome="/index" value="Retour à la page d'accueil" /></li>
                </ul>
            </p>
        </f:view>
    </h:body>
</html>